import itertools

import numpy as np
import pandas as pd

from baseball.duckdb.tables import TABLES
from baseball.projects.strategery.constants import (
    GAME_STATES_FULL,
    MAX_RUNS_PER_INNING,
    RE24_DUCK_DB_PARQUET_PATH,
    RUNS_ARRAY,
)
from baseball.utils.duckdb import query

TRANSITION_STATES = [
    "_".join((x, str(y))) for x, y in (itertools.product(GAME_STATES_FULL, np.arange(0, MAX_RUNS_PER_INNING + 1)))
]


def load_pa_data() -> pd.DataFrame:
    """
    Query Savant pitch data from DuckDB to build play-by-play plate appearance records.

    This function aggregates pitch-level data into plate appearance (PA) level data,
    calculating the baseball game state (bases occupied and outs) before each PA,
    along with the current score and event outcomes.

    Returns
    -------
    pd.DataFrame
        A DataFrame containing plate appearance level data, including game state,
        inning, score, and play description.
    """

    sql = f"""
    WITH first_pitch AS (
        SELECT
            game_pk,
            at_bat_number,
            MIN(pitch_number) pitch_number,
        FROM '{TABLES.pitch.savant}'
        GROUP BY
            game_pk,
            at_bat_number
    ),
    last_pitch AS (
        SELECT
            game_pk,
            at_bat_number,
            MAX(pitch_number) pitch_number,
        FROM '{TABLES.pitch.savant}'
        GROUP BY
            game_pk,
            at_bat_number
    ),
    pa AS (
        SELECT
            p.game_pk,
            p.at_bat_number,
            p.pitch_number,
            p.events,
            p.description,
            p.des
        FROM '{TABLES.pitch.savant}' p
        JOIN last_pitch AS lp USING(game_pk, at_bat_number, pitch_number)
    )
    SELECT
        p.season,
        p.game_pk,
        p.inning_topbot,
        p.inning,
        p.at_bat_number,
        p.pitch_number,
        p.balls,
        p.strikes,
        -- p.on_1b,
        -- p.on_2b,
        -- p.on_3b,
        p.outs_when_up,
        CONCAT(
            IF(on_1b IS NULL, '-', '1'),
            IF(on_2b IS NULL, '-', '2'),
            IF(on_3b IS NULL, '-', '3'),
            ':',
            outs_when_up
        ) AS game_state,
        p.bat_score,
        p.home_score,
        p.away_score,
        p.home_score - p.away_score AS home_lead,
        pa.events,
        pa.description,
        pa.des AS description_full


    FROM '{TABLES.pitch.savant}' p
    JOIN first_pitch fp USING(game_pk, at_bat_number, pitch_number)
    JOIN pa ON
        p.game_pk = pa.game_pk AND
        p.at_bat_number = pa.at_bat_number
    -- WHERE p.game_pk = 526517
    ORDER BY
        p.game_pk,
        p.inning,
        p.at_bat_number,
        p.pitch_number
    """
    pa_df = query(sql)
    return pa_df


def widen_pa_data(pa_df: pd.DataFrame) -> pd.DataFrame:
    """
    Merge plate appearance data with the subsequent plate appearance to map state transitions.

    This function aligns each PA with the PA that immediately followed it (PA + 1) to
    determine the resulting game state (`game_state_post`) and calculate how many runs
    scored during the play.

    Parameters
    ----------
    pa_df : pd.DataFrame
        The base plate appearance DataFrame generated by `load_pa_data`.

    Returns
    -------
    pd.DataFrame
        A widened DataFrame where each row contains data for a given PA as well as the
        state of the game at the start of the next PA, including runs scored on the play.
    """
    # copy dataframe to merge
    pa_df_ = pa_df.copy()

    # decrement at bat index to join
    pa_df_["at_bat_number"] -= 1

    # merge PA, PA + 1
    shifted_pa_df = pa_df.merge(pa_df_, on=["season", "game_pk", "at_bat_number"], suffixes=["", "_post"]).drop(
        columns=["description_post", "description_full_post", "events_post"]
    )

    # fill in inning enders as game_state_post = ---:3
    shifted_pa_df["game_state_post"] = np.where(
        shifted_pa_df["inning_topbot"].values != shifted_pa_df["inning_topbot_post"].values,
        "---:3",
        shifted_pa_df["game_state_post"].values,
    )

    # calculate runs scored on the play
    shifted_pa_df["runs"] = np.where(
        shifted_pa_df["inning_topbot"].values == "Bot",
        shifted_pa_df["home_score_post"].values - shifted_pa_df["home_score"].values,
        shifted_pa_df["away_score_post"].values - shifted_pa_df["away_score"].values,
    )

    return shifted_pa_df


def calculate_empirical_transition_probs(shifted_pa_df: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate the historical probability of transitioning from one game state to another.

    Parameters
    ----------
    shifted_pa_df : pd.DataFrame
        The widened plate appearance DataFrame containing initial states,
        post-states, and runs scored.

    Returns
    -------
    pd.DataFrame
        A DataFrame containing the unique state transitions, the frequency of each
        transition (`n`), the total occurrences of the starting state (`n_tot`),
        and the resulting empirical probability (`pi`).
    """
    # count the number of state transitions
    empirical_transition_probs = (
        shifted_pa_df.assign(n=1).groupby(["game_state", "game_state_post", "runs"], as_index=False)["n"].sum()
    )

    # calculate number of transitions "from" each state, to use as denomenator in the empirical probs
    denoms = empirical_transition_probs.groupby(["game_state"], as_index=False)["n"].sum()
    empirical_transition_probs = empirical_transition_probs.merge(denoms, on="game_state", suffixes=["", "_tot"])

    # calculate empirical probs
    empirical_transition_probs["prob"] = empirical_transition_probs.n / empirical_transition_probs.n_tot
    return empirical_transition_probs


def make_transition_matrix(empirical_transition_probs: pd.DataFrame) -> pd.DataFrame:
    """
    Build a Markov transition matrix for the expanded game state space.

    The expanded state space tracks both the traditional 24 base/out states and
    the number of runs scored in the inning up to `MAX_RUNS_PER_INNING`.

    Parameters
    ----------
    empirical_transition_probs : pd.DataFrame
        The historical transition probabilities calculated by
        `calculate_empirical_transition_probs`.

    Returns
    -------
    pd.DataFrame
        A square, row-stochastic transition matrix (P) where the index and columns
        represent the expanded game states (e.g., '1-3:1_2' for 1st/3rd, 1 out, 2 runs).
    """
    # initialize a transition matrix in the "expanded" state space -- states are defined by
    # (game_state, runs_scored_in_inning)
    P = pd.DataFrame(
        np.zeros((25 * (MAX_RUNS_PER_INNING + 1),) * 2), index=TRANSITION_STATES, columns=TRANSITION_STATES
    )

    # iterate through runs scored in inning (half of the expanded state definition)
    for runs in range(0, MAX_RUNS_PER_INNING):
        # iterate through game states (other half of the expanded state definition)
        for _, row in empirical_transition_probs.iterrows():
            # clip runs scored after -- innings roll at `MAX_RUNS_PER_INNING`, so a 3-run HR up 14 is the same
            # as just going to 15.
            runs_post = min(runs + row["runs"], MAX_RUNS_PER_INNING)

            # update the probability for that transition
            P.loc[row["game_state"] + "_" + str(runs), row["game_state_post"] + "_" + str(runs_post)] += row["prob"]
        # ensure terminal states remain stuck where they are
        P.loc["---:3_" + str(runs), "---:3_" + str(runs)] = 1.0

    # whenever you've reached `MAX_RUNS_PER_INNING`, next transition is automatically to terminal state
    for game_state in GAME_STATES_FULL:
        P.loc[game_state + "_" + str(MAX_RUNS_PER_INNING), "---:3_" + str(MAX_RUNS_PER_INNING)] = 1.0

    # make sure row stochastic
    assert np.all(np.isclose(P.values.sum(axis=1), 1.0))

    return P


def calculate_re24_from_transition_matrix(P: pd.DataFrame) -> pd.DataFrame:
    """
    Compute Run Expectancy (RE24) exactly using Absorbing Markov Chain properties.

    This function calculates the exact expected runs from any given base/out state
    by treating the end of an inning (3 outs) as an absorbing state. It partitions
    the expanded transition matrix into transient (Q) and absorbing (R) matrices,
    and uses linear algebra to solve for the final absorption probabilities directly,
    avoiding the need for iterative simulation.

    Parameters
    ----------
    P : pd.DataFrame
        The expanded Markov transition matrix containing transition probabilities for
        both transient states (ongoing inning) and absorbing states (inning over).
        The index and columns must match `TRANSITION_STATES`.

    Returns
    -------
    pd.DataFrame
        A DataFrame containing the 24 standard base/out states, the probability
        distribution of exact run totals scored from that point forward, and the
        final calculated expected runs (`run_exp`).

    Notes
    -----
    Just solving for absorbing probabilities matrix ($B$):

    $B = (I - Q)^{-1} R$
    """
    # identify transient (non-terminal) and absorbing (terminal) states
    transient_states = [state for state in TRANSITION_STATES if not state.startswith("---:3")]
    absorbing_states = [state for state in TRANSITION_STATES if state.startswith("---:3")]

    # extract Q (transient-to-transient) and R (transient-to-absorbing) matrices
    Q = P.loc[transient_states, transient_states].values
    R = P.loc[transient_states, absorbing_states].values

    # make id matrix
    I = np.eye(len(Q))

    # solve for the absorbing probabilities directly: B = (I - Q)^-1 * R
    B = np.linalg.solve(I - Q, R)

    # stuff into a DataFrame for easy slicing
    B_df = pd.DataFrame(B, index=transient_states, columns=absorbing_states)

    # slice down to the 24 base/out states at 0 runs scored
    re24_states = [item + "_0" for item in GAME_STATES_FULL if item != "---:3"]
    re24 = B_df.loc[re24_states].copy()

    # name the columns by the runs scored (p_0 through p_<MAX_RUNS_PER_INNING>)
    re24.columns = ["p_" + str(item) for item in RUNS_ARRAY]

    # calculate RE24 by taking the dot product of probabilities and runs
    re24["run_exp"] = re24.values @ RUNS_ARRAY

    # clean up the game_state column for readability
    re24 = re24.reset_index().rename(columns={"index": "game_state"})
    re24["game_state"] = [item.replace("_0", "") for item in re24["game_state"]]

    return re24


def calculate_re24(group_half_innings: bool = True) -> pd.DataFrame:
    """
    Execute the full pipeline to calculate the RE24 (Run Expectancy) matrix.

    Pulls raw data, formats the game states, computes transition probabilities
    for regular innings (1st through top of the 9th), builds the Markov chain,
    and outputs the final expected runs by state.

    Returns
    -------
    pd.DataFrame
        The final RE24 matrix with base/out states and expected runs.
    """

    def _do_calcs(shifted_pa_df: pd.DataFrame) -> pd.DataFrame:
        empirical_transition_probs = calculate_empirical_transition_probs(shifted_pa_df)
        P = make_transition_matrix(empirical_transition_probs)
        re24 = calculate_re24_from_transition_matrix(P)
        return re24

    shifted_pa_df = load_pa_data().pipe(widen_pa_data).query("(inning < 9) | (inning == 9 & inning_topbot == 'Top')")
    if group_half_innings:
        re24 = pd.concat(
            [_do_calcs(df).assign(inning_topbot=inn_tb) for (inn_tb,), df in shifted_pa_df.groupby(["inning_topbot"])],
            axis=0,
        ).reset_index(drop=True)
    else:
        re24 = _do_calcs(shifted_pa_df)
    return re24


def calculate_and_save_re24() -> None:
    """Calculates the RE24 values and saves them to the duckdb folderpath"""
    re24 = calculate_re24()
    re24.to_parquet(RE24_DUCK_DB_PARQUET_PATH)


if __name__ == "__main__":
    calculate_and_save_re24()
